const CATEGORY={
  mtb:{label:'MTB',color:'#2f7d4a'},nordic:{label:'Nordic',color:'#1779a8'},'road-races':{label:'Road race',color:'#d97706'},'trail-races':{label:'Trail race',color:'#b45309'},skiing:{label:'Skiing',color:'#16a6c9'},summits:{label:'Summit',color:'#16836d'},adventures:{label:'Adventure',color:'#8b5cf6'}
};
const state={adventures:[],routes:null,filter:'all',search:'',yearFrom:null,yearTo:null,markers:new Map(),routeLayers:new Map(),routeFeatureLayers:new Map(),focusId:null,pinnedFocusId:null};
const DEFAULT_MAP_VIEW={center:[39,-105.5],zoom:2};
const map=L.map('map',{worldCopyJump:true,zoomControl:true,minZoom:2}).setView(DEFAULT_MAP_VIEW.center,DEFAULT_MAP_VIEW.zoom);window.adventureMap=map;window.stabilizeLeafletMap?.(map,document.getElementById('map'));L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const routeLayer=L.layerGroup().addTo(map),markerLayer=L.layerGroup().addTo(map),focusEndpointLayer=L.layerGroup().addTo(map),searchInput=document.getElementById('searchInput'),fitButton=document.getElementById('fitButton'),adventureList=document.getElementById('adventureList'),resultCount=document.getElementById('resultCount'),resultsSection=document.querySelector('.results-section'),yearFrom=document.getElementById('yearFrom'),yearTo=document.getElementById('yearTo'),yearReset=document.getElementById('yearReset');
function publicLayerFor(a){if(a.kind==='summit')return'summits';if(a.kind==='adventure')return'adventures';if(a.mapCategory==='ski'||a.discipline==='ski')return'skiing';if(a.discipline==='mountain-bike'||a.mapCategory==='mountain-bike'||a.mapCategory==='downhill-mtb')return'mtb';if(a.discipline==='nordic'||a.mapCategory==='nordic')return'nordic';if(a.kind==='race'&&a.discipline==='trail')return'trail-races';if(a.kind==='race')return'road-races';return a.kind==='event'&&a.discipline==='nordic'?'nordic':'adventures'}
function mapped(a){return Number.isFinite(a.lat)&&Number.isFinite(a.lon)}
function recordYear(a){const y=Number(a.year||String(a.date||'').slice(0,4));return Number.isFinite(y)&&y>1900?y:null}
function recordHref(a){return location.hostname==='adventures.alexlford.com'?`/record/${encodeURIComponent(a.slug||a.id)}/`:`detail.html?record=${encodeURIComponent(a.slug||a.id)}`}
function formatNumber(v){return new Intl.NumberFormat('en-US').format(v)}
function formatDate(v){if(!v)return'';const[y,m,d]=v.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(y,m-1,d))}
function formatDuration(s){if(!Number.isFinite(s)||s<=0)return'';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=Math.floor(s%60);return h?`${h}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${m}:${String(x).padStart(2,'0')}`}
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function renderArchiveState(kind,title,detail=''){adventureList.innerHTML=`<div class="archive-state archive-state-${escapeHtml(kind)}" role="${kind==='error'?'alert':'status'}"><strong>${escapeHtml(title)}</strong>${detail?`<span>${escapeHtml(detail)}</span>`:''}</div>`}
function subtypeFor(a){if(a.mapCategory==='downhill-mtb')return'Downhill MTB';if(a.kind==='race'&&a.discipline==='marathon')return'Marathon';if(a.kind==='race'&&a.discipline==='relay')return'Relay';if(a.kind==='race'&&a.discipline==='nordic')return'Nordic race';if(a.kind==='event'&&a.discipline==='nordic')return'Nordic event';if(a.kind==='outing'&&a.discipline==='mountain-bike')return a.mtbMode==='downhill'?'Downhill MTB':'MTB outing';if(a.kind==='outing'&&a.discipline==='nordic')return'Nordic outing';return CATEGORY[publicLayerFor(a)]?.label||'Adventure'}
function searchText(a){return[a.name,a.currentName,a.year,a.date,a.location,a.region,a.distance,a.distanceMi,a.elevationFt,a.stravaActivityName,publicLayerFor(a),subtypeFor(a)].filter(Boolean).join(' ').toLowerCase()}
function filteredAdventures(){const q=state.search.trim().toLowerCase();return state.adventures.filter(a=>{const y=recordYear(a);const yearOk=(!state.yearFrom||!y||y>=state.yearFrom)&&(!state.yearTo||!y||y<=state.yearTo);return(state.filter==='all'||publicLayerFor(a)===state.filter)&&yearOk&&(!q||searchText(a).includes(q))})}
function popupCard(a){const primary=a.kind==='summit'?`${formatNumber(a.elevationFt)} ft`:a.kind==='adventure'?(a.distance||''):[a.year,a.distance].filter(Boolean).join(' · ');const alias=a.currentName?`<p class="popup-alias">Now known as ${escapeHtml(a.currentName)}</p>`:'';const date=a.date?`<p class="popup-meta">${escapeHtml(formatDate(a.date))}${a.endDate?` – ${escapeHtml(formatDate(a.endDate))}`:''}</p>`:'';const showGain=a.mapCategory!=='downhill-mtb'&&a.mtbMode!=='downhill';const metrics=a.distanceMi?`<p class="popup-meta">${escapeHtml(a.distanceMi)} mi${showGain&&a.elevationGainM?` · ${escapeHtml(Math.round(a.elevationGainM))} m gain`:''}${a.elapsedSeconds?` · ${escapeHtml(formatDuration(a.elapsedSeconds))} elapsed`:''}</p>`:'';return `<article class="popup-card"><p class="popup-kicker">${escapeHtml(subtypeFor(a))}</p><h3 class="popup-title">${escapeHtml(a.name)}</h3>${alias}<p class="popup-meta">${escapeHtml(primary)}${primary?' · ':''}${escapeHtml(a.location)}</p>${date}${metrics}<p class="popup-detail"><a href="${recordHref(a)}">Open record →</a></p></article>`}
function coordinateKey(a){return`${a.lat.toFixed(5)},${a.lon.toFixed(5)}`}
const markerGridSize=zoom=>zoom<=3?52:zoom===4?42:zoom===5?32:zoom===6?24:0;
function groupCenter(group){const lat=group.reduce((sum,item)=>sum+item.lat,0)/group.length,lon=group.reduce((sum,item)=>sum+item.lon,0)/group.length;return[lat,lon]}
function markerGroupKey(a,zoom,grid){if(!grid)return coordinateKey(a);const point=map.project([a.lat,a.lon],zoom);return`${Math.floor(point.x/grid)},${Math.floor(point.y/grid)}`}
function markerPopup(group){const ordered=group.slice().sort((a,b)=>(recordYear(b)||0)-(recordYear(a)||0)||a.name.localeCompare(b.name));const shown=ordered.slice(0,8).map(popupCard).join('');const more=ordered.length>8?`<p class="map-cluster-more">+ ${ordered.length-8} more nearby records · zoom in to separate them.</p>`:'';return shown+more}
function clusterBounds(group){const bounds=L.latLngBounds([]);group.forEach(item=>bounds.extend([item.lat,item.lon]));return bounds}
function renderMarkers(items){markerLayer.clearLayers();state.markers.clear();const zoom=map.getZoom(),grid=markerGridSize(zoom),groups=new Map();items.filter(mapped).forEach(a=>{const key=markerGroupKey(a,zoom,grid);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(a)});groups.forEach(group=>{const categories=[...new Set(group.map(publicLayerFor))],mixed=categories.length>1,category=mixed?null:categories[0],color=mixed?'#59636d':CATEGORY[category]?.color||CATEGORY.adventures.color,cluster=Boolean(grid&&group.length>1),center=cluster?groupCenter(group):[group[0].lat,group[0].lon],baseRadius=cluster?Math.min(14,5.2+Math.sqrt(group.length)*1.9):(group.length>1?8:6),marker=L.circleMarker(center,{radius:baseRadius,color:'#fff',weight:mixed?2.5:2,fillColor:color,fillOpacity:.9,bubblingMouseEvents:false});marker.__adventureBaseRadius=baseRadius;marker.__adventureMixed=mixed;marker.__adventureCluster=cluster;marker.addTo(markerLayer);if(cluster){marker.bindTooltip(String(group.length),{permanent:true,direction:'center',className:'map-cluster-count',opacity:1});marker.on('click',()=>{state.pinnedFocusId=null;state.focusId=null;applyFocusStyles();const bounds=clusterBounds(group),targetZoom=Math.min(8,zoom+2),unique=new Set(group.map(coordinateKey)).size;if(unique>1&&bounds.isValid())map.fitBounds(bounds,{padding:[52,52],maxZoom:targetZoom});else map.setView(center,targetZoom)})}else{marker.bindPopup(markerPopup(group),{maxWidth:360});if(group.length>1)marker.bindTooltip(String(group.length),{permanent:true,direction:'center',className:'map-cluster-count',opacity:1});else marker.bindTooltip(group[0].name,{direction:'top',offset:[0,-5],opacity:.94,className:'map-point-label'});if(group.length===1){const record=group[0];marker.on('mouseover',()=>setRouteEmphasis(record.id,true));marker.on('mouseout',()=>setRouteEmphasis(record.id,false));marker.on('click',()=>{state.pinnedFocusId=record.id;state.focusId=record.id;applyFocusStyles()})}}marker.on('add',()=>{const node=marker.getElement?.();if(!node)return;const label=cluster?`${group.length} nearby adventure records`:(group.length>1?`${group.length} records at this location`:group[0].name);node.setAttribute('aria-label',label)});group.forEach(record=>state.markers.set(record.id,marker))})}
function visibleRouteFeatures(items){if(!state.routes)return[];const ids=new Set(items.map(a=>a.id));return state.routes.features.filter(f=>(f.properties?.adventureIds||[]).some(id=>ids.has(id)))}
function baseRouteStyle(feature,category){const historical=feature.properties?.provenance==='historical-course';return{color:CATEGORY[category]?.color||'#17202a',weight:category==='summits'?3:4.5,opacity:historical?.64:.84,dashArray:historical?'8 6':null,lineCap:'round',lineJoin:'round'}}
function routeContainsId(layer,id){return(layer.feature?.properties?.adventureIds||[]).includes(id)}
function geometrySegments(geometry){if(!geometry)return[];if(geometry.type==='LineString')return[geometry.coordinates||[]];if(geometry.type==='MultiLineString')return geometry.coordinates||[];if(geometry.type==='GeometryCollection')return(geometry.geometries||[]).flatMap(geometrySegments);return[]}
function segmentLength(segment){let total=0;for(let i=1;i<segment.length;i+=1){const[x1,y1]=segment[i-1],[x2,y2]=segment[i];if(![x1,y1,x2,y2].every(Number.isFinite))continue;const dx=(x2-x1)*Math.cos(((y1+y2)/2)*Math.PI/180),dy=y2-y1;total+=Math.hypot(dx,dy)}return total}
function endpointIcon(kind,color){const label=kind==='loop'?'↻':kind==='start'?'S':'F',cls=`route-endpoint ${kind==='finish'?'is-finish':''}${kind==='loop'?' is-loop':''}`;return L.divIcon({className:'route-endpoint-wrap',html:`<span class="${cls}" style="--route-color:${color}">${label}</span>`,iconSize:[26,26],iconAnchor:[13,13]})}
function renderFocusEndpoints(){focusEndpointLayer.clearLayers();if(!state.focusId)return;const record=state.adventures.find(a=>a.id===state.focusId);if(!record)return;const segments=visibleRouteFeatures([record]).flatMap(feature=>geometrySegments(feature.geometry)).filter(segment=>segment.length>1);if(!segments.length)return;const segment=segments.slice().sort((a,b)=>segmentLength(b)-segmentLength(a))[0],start=segment[0],finish=segment[segment.length-1];if(!start||!finish)return;const[startLon,startLat]=start,[finishLon,finishLat]=finish;if(![startLon,startLat,finishLon,finishLat].every(Number.isFinite))return;const color=window.AdventureMapTheme?.routeColor?.(record)||CATEGORY[publicLayerFor(record)]?.color||'#17202a',dx=(finishLon-startLon)*Math.cos(((startLat+finishLat)/2)*Math.PI/180),dy=finishLat-startLat,loop=Math.hypot(dx,dy)<.00065;if(loop){L.marker([startLat,startLon],{icon:endpointIcon('loop',color),interactive:false,zIndexOffset:900}).bindTooltip('Start / finish',{direction:'top',offset:[0,-10],className:'route-endpoint-label'}).addTo(focusEndpointLayer);return}L.marker([startLat,startLon],{icon:endpointIcon('start',color),interactive:false,zIndexOffset:900}).bindTooltip('Start',{direction:'top',offset:[0,-10],className:'route-endpoint-label'}).addTo(focusEndpointLayer);L.marker([finishLat,finishLon],{icon:endpointIcon('finish',color),interactive:false,zIndexOffset:900}).bindTooltip('Finish',{direction:'top',offset:[0,-10],className:'route-endpoint-label'}).addTo(focusEndpointLayer)}
function applyFocusStyles(){if(state.pinnedFocusId&&!pinnedIsVisible())state.pinnedFocusId=null;if(state.focusId&&!state.adventures.some(a=>a.id===state.focusId))state.focusId=null;if(!state.focusId&&state.pinnedFocusId)state.focusId=state.pinnedFocusId;const zoom=map.getZoom(),low=zoom<=4,mid=zoom>4&&zoom<=6,routeWeightFactor=low?.5:(mid?.72:1),routeOpacityFactor=low?.48:(mid?.7:1),pointRadius=low?4.3:(mid?5.2:6);state.routeFeatureLayers.forEach(group=>group.eachLayer(layer=>{const feature=layer.feature||{},linked=(feature.properties?.adventureIds||[]).map(x=>state.adventures.find(a=>a.id===x)).filter(Boolean),category=publicLayerFor(linked[0]||{kind:'adventure'}),style=baseRouteStyle(feature,category),active=state.focusId&&routeContainsId(layer,state.focusId),weight=active?Math.max(style.weight+3,7):Math.max(1.5,style.weight*routeWeightFactor),opacity=state.focusId?(active?1:.1):Math.max(.22,style.opacity*routeOpacityFactor);layer.setStyle?.({...style,weight,opacity});if(active)layer.bringToFront?.()}));const groupedMarkers=new Map();state.markers.forEach((marker,id)=>{if(!groupedMarkers.has(marker))groupedMarkers.set(marker,[]);groupedMarkers.get(marker).push(id)});groupedMarkers.forEach((ids,marker)=>{const records=ids.map(id=>state.adventures.find(a=>a.id===id)).filter(Boolean),mixed=marker.__adventureMixed??new Set(records.map(publicLayerFor)).size>1,active=Boolean(state.focusId&&ids.includes(state.focusId)),fallbackRadius=pointRadius+(ids.length>1?1.6:0),baseRadius=marker.__adventureBaseRadius||fallbackRadius;marker.setStyle?.({radius:active?baseRadius+3:baseRadius,weight:active?3:(mixed?2.5:(low?1.5:2)),fillOpacity:state.focusId?(active?.98:.22):(low?.82:.9),opacity:state.focusId?(active?1:.3):(low?.9:1)});if(active)marker.bringToFront?.()});renderFocusEndpoints();document.querySelectorAll('.adventure-item').forEach(el=>el.classList.toggle('is-context-muted',Boolean(state.focusId)&&el.dataset.id!==state.focusId))}
function pinnedIsVisible(){return Boolean(state.pinnedFocusId&&filteredAdventures().some(a=>a.id===state.pinnedFocusId))}
function setRouteEmphasis(id,on){if(on)state.focusId=id;else{if(!pinnedIsVisible())state.pinnedFocusId=null;state.focusId=state.pinnedFocusId||null}applyFocusStyles()}
function renderRoutes(items){routeLayer.clearLayers();state.routeLayers.clear();state.routeFeatureLayers.clear();state.focusId=null;visibleRouteFeatures(items).forEach(feature=>{const linked=(feature.properties?.adventureIds||[]).map(id=>state.adventures.find(x=>x.id===id)).filter(Boolean),category=publicLayerFor(linked[0]||{kind:'adventure'});const geo=L.geoJSON(feature,{style:baseRouteStyle(feature,category),onEachFeature:(f,layer)=>{layer.on('mouseover',()=>{const id=(f.properties?.adventureIds||[])[0];if(id)setRouteEmphasis(id,true)});layer.on('mouseout',()=>{const id=(f.properties?.adventureIds||[])[0];if(id)setRouteEmphasis(id,false)})}}).addTo(routeLayer);if(linked.length)geo.bindPopup(linked.map(popupCard).join(''),{maxWidth:360});(feature.properties?.adventureIds||[]).forEach(id=>{if(!state.routeLayers.has(id))state.routeLayers.set(id,[]);state.routeLayers.get(id).push(geo)});const fid=feature.id||feature.properties?.featureId||feature.properties?.id;if(fid)state.routeFeatureLayers.set(fid,geo)})}
function itemMeta(a){return[a.date?formatDate(a.date):'',a.location,subtypeFor(a),a.currentName?`now ${a.currentName}`:''].filter(Boolean).join(' · ')}
function itemValue(a){if(a.kind==='summit')return`${formatNumber(a.elevationFt)}′`;if(a.kind==='adventure')return a.distance||a.distanceMi?`${a.distanceMi||''}${a.distanceMi?' mi':''}`.trim():'';if(a.distanceMi)return`${a.distanceMi} mi`;return[a.year,a.distance].filter(Boolean).join(' · ')}
function focusAdventure(a){state.pinnedFocusId=a.id;state.focusId=a.id;applyFocusStyles();const groups=state.routeLayers.get(a.id)||[];if(groups.length){const bounds=L.latLngBounds([]);groups.forEach(g=>g.eachLayer(layer=>{if(layer.getBounds)bounds.extend(layer.getBounds())}));if(bounds.isValid())map.fitBounds(bounds,{padding:[46,46],maxZoom:13});groups[0].openPopup?.();return}if(mapped(a)){const openFocused=()=>{if(state.pinnedFocusId!==a.id)return;state.focusId=a.id;applyFocusStyles();state.markers.get(a.id)?.openPopup?.()};map.once('moveend',openFocused);map.flyTo([a.lat,a.lon],Math.max(map.getZoom(),a.kind==='summit'?9:8),{duration:.8});setTimeout(openFocused,900)}}
function renderList(items){resultCount.textContent=`${items.length} shown`;adventureList.innerHTML='';if(!items.length){renderArchiveState('empty','No matching records','Try another layer, year range, or search.');return}items.slice().sort((a,b)=>{const ay=recordYear(a)||0,by=recordYear(b)||0;if(by!==ay)return by-ay;if(a.kind!==b.kind)return a.kind==='summit'?-1:1;if(a.kind==='summit')return(b.elevationFt??0)-(a.elevationFt??0);return a.name.localeCompare(b.name)}).forEach(a=>{const category=publicLayerFor(a),button=document.createElement('button');button.type='button';button.dataset.id=a.id;button.className=`adventure-item${mapped(a)||state.routeLayers.has(a.id)?'':' is-unmapped'}`;button.innerHTML=`<span class="item-dot" style="background:${CATEGORY[category]?.color||CATEGORY.adventures.color}"></span><span><span class="item-title">${escapeHtml(a.name)}</span><span class="item-meta">${escapeHtml(itemMeta(a))}</span></span><span class="item-value">${escapeHtml(itemValue(a))}</span>`;if(mapped(a)||state.routeLayers.has(a.id)){button.addEventListener('click',()=>focusAdventure(a));button.addEventListener('mouseenter',()=>setRouteEmphasis(a.id,true));button.addEventListener('mouseleave',()=>setRouteEmphasis(a.id,false));button.addEventListener('focus',()=>setRouteEmphasis(a.id,true));button.addEventListener('blur',()=>setRouteEmphasis(a.id,false))}adventureList.appendChild(button)})}
function walkCoordinates(coords,bounds){if(!Array.isArray(coords))return;if(typeof coords[0]==='number'){const[lon,lat]=coords;if(Number.isFinite(lat)&&Number.isFinite(lon))bounds.extend([lat,lon]);return}coords.forEach(c=>walkCoordinates(c,bounds))}
function fitVisible(items){state.focusId=null;const bounds=L.latLngBounds([]);items.filter(mapped).forEach(x=>bounds.extend([x.lat,x.lon]));visibleRouteFeatures(items).forEach(f=>walkCoordinates(f.geometry?.coordinates,bounds));if(bounds.isValid())map.fitBounds(bounds,{padding:[38,38],maxZoom:8});applyFocusStyles()}
function render(){const pinned=state.pinnedFocusId,items=filteredAdventures();renderRoutes(items);renderMarkers(items);renderList(items);if(pinned&&items.some(a=>a.id===pinned))state.focusId=pinned;else if(pinned)state.pinnedFocusId=null;requestAnimationFrame(()=>applyFocusStyles())}
function renderPreservingFocus(){const focusId=state.focusId,focused=focusId?state.adventures.find(a=>a.id===focusId):null;render();if(focused&&filteredAdventures().some(a=>a.id===focusId))focusAdventure(focused)}
function applyAndFit(){render();fitVisible(filteredAdventures())}
function initYearControls(){const years=[...new Set(state.adventures.map(recordYear).filter(Boolean))].sort((a,b)=>a-b);const options=years.map(y=>`<option value="${y}">${y}</option>`).join('');yearFrom.insertAdjacentHTML('beforeend',options);yearTo.insertAdjacentHTML('beforeend',options);yearFrom.addEventListener('change',()=>{state.yearFrom=yearFrom.value?Number(yearFrom.value):null;if(state.yearTo&&state.yearFrom&&state.yearFrom>state.yearTo){state.yearTo=state.yearFrom;yearTo.value=String(state.yearTo)}applyAndFit()});yearTo.addEventListener('change',()=>{state.yearTo=yearTo.value?Number(yearTo.value):null;if(state.yearFrom&&state.yearTo&&state.yearTo<state.yearFrom){state.yearFrom=state.yearTo;yearFrom.value=String(state.yearFrom)}applyAndFit()});yearReset.addEventListener('click',()=>{state.yearFrom=null;state.yearTo=null;yearFrom.value='';yearTo.value='';applyAndFit()})}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{state.filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('is-active',x===button));applyAndFit()}));searchInput.addEventListener('input',()=>{state.search=searchInput.value;render()});searchInput.addEventListener('keydown',e=>{if(e.key==='Enter')fitVisible(filteredAdventures())});fitButton.addEventListener('click',()=>fitVisible(filteredAdventures()));map.on('click',()=>{state.pinnedFocusId=null;state.focusId=null;applyFocusStyles()});
renderArchiveState('loading','Loading map archive','Preparing routes and locations.');resultCount.textContent='Loading';resultsSection?.setAttribute('aria-busy','true');
async function init(){try{const[adventures,rRes]=await Promise.all([AdventureCatalog.load(),fetch('data/routes.geojson')]);if(!rRes.ok)throw new Error('Unable to load map routes');state.adventures=adventures;state.routes=await AdventureRoutes.normalizeCollection(await rRes.json());document.getElementById('summitCount').textContent=state.adventures.filter(x=>x.kind==='summit').length;document.getElementById('raceCount').textContent=state.adventures.filter(x=>x.kind==='race').length;document.getElementById('routeCount').textContent=new Set(state.routes.features.flatMap(f=>f.properties?.adventureIds||[])).size;initYearControls();render();resultsSection?.setAttribute('aria-busy','false');setTimeout(()=>map.invalidateSize({pan:false}),100)}catch(error){resultCount.textContent='Unavailable';resultsSection?.setAttribute('aria-busy','false');renderArchiveState('error','Map archive unavailable',error.message);console.error(error)}}init();
