const A=window.AdventureSite;
if(!A)throw new Error('AdventureSite shared helpers are unavailable');
const formatNumber=v=>A.fmt.format(v),formatDate=A.formatDate,formatDuration=A.formatDuration,escapeHtml=A.esc,recordHref=A.recordHref;
const CATEGORY={
  mtb:{label:'MTB',color:'#2563eb'},nordic:{label:'Nordic',color:'#1779a8'},'road-races':{label:'Road race',color:'#d97706'},'trail-races':{label:'Trail race',color:'#b45309'},skiing:{label:'Skiing',color:'#16a6c9'},summits:{label:'Summit',color:'#16836d'},adventures:{label:'Adventure',color:'#8b5cf6'}
};
const state={adventures:[],routes:null,filter:'all',search:'',yearFrom:null,yearTo:null,markers:new Map(),routeLayers:new Map(),routeFeatureLayers:new Map(),focusId:null};
const map=L.map('map',{worldCopyJump:true,zoomControl:true,minZoom:2}).setView([34,-112],3);window.adventureMap=map;window.stabilizeLeafletMap?.(map,document.getElementById('map'));L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const routeLayer=L.layerGroup().addTo(map),markerLayer=L.layerGroup().addTo(map),searchInput=document.getElementById('searchInput'),fitButton=document.getElementById('fitButton'),adventureList=document.getElementById('adventureList'),resultCount=document.getElementById('resultCount'),yearFrom=document.getElementById('yearFrom'),yearTo=document.getElementById('yearTo'),yearReset=document.getElementById('yearReset');
function publicLayerFor(a){if(a.kind==='summit')return'summits';if(a.kind==='adventure')return'adventures';if(a.mapCategory==='ski'||a.discipline==='ski')return'skiing';if(a.discipline==='mountain-bike'||a.mapCategory==='mountain-bike'||a.mapCategory==='downhill-mtb')return'mtb';if(a.discipline==='nordic'||a.mapCategory==='nordic')return'nordic';if(a.kind==='race'&&a.discipline==='trail')return'trail-races';if(a.kind==='race')return'road-races';return a.kind==='event'&&a.discipline==='nordic'?'nordic':'adventures'}
function mapped(a){return Number.isFinite(a.lat)&&Number.isFinite(a.lon)}
function recordYear(a){const y=Number(a.year||String(a.date||'').slice(0,4));return Number.isFinite(y)&&y>1900?y:null}
function subtypeFor(a){if(a.mapCategory==='downhill-mtb')return'Downhill MTB';if(a.kind==='race'&&a.discipline==='marathon')return'Marathon';if(a.kind==='race'&&a.discipline==='relay')return'Relay';if(a.kind==='race'&&a.discipline==='nordic')return'Nordic race';if(a.kind==='event'&&a.discipline==='nordic')return'Nordic event';if(a.kind==='outing'&&a.discipline==='mountain-bike')return a.mtbMode==='downhill'?'Downhill MTB':'MTB outing';if(a.kind==='outing'&&a.discipline==='nordic')return'Nordic outing';return CATEGORY[publicLayerFor(a)]?.label||'Adventure'}
function searchText(a){return[a.name,a.currentName,a.year,a.date,a.location,a.region,a.distance,a.distanceMi,a.elevationFt,a.stravaActivityName,publicLayerFor(a),subtypeFor(a)].filter(Boolean).join(' ').toLowerCase()}
function filteredAdventures(){const q=state.search.trim().toLowerCase();return state.adventures.filter(a=>{const y=recordYear(a);const yearOk=(!state.yearFrom||!y||y>=state.yearFrom)&&(!state.yearTo||!y||y<=state.yearTo);return(state.filter==='all'||publicLayerFor(a)===state.filter)&&yearOk&&(!q||searchText(a).includes(q))})}
function popupCard(a){const primary=a.kind==='summit'?`${formatNumber(a.elevationFt)} ft`:a.kind==='adventure'?(a.distance||''):[a.year,a.distance].filter(Boolean).join(' · ');const alias=a.currentName?`<p class="popup-alias">Now known as ${escapeHtml(a.currentName)}</p>`:'';const date=a.date?`<p class="popup-meta">${escapeHtml(formatDate(a.date))}${a.endDate?` – ${escapeHtml(formatDate(a.endDate))}`:''}</p>`:'';const showGain=a.mapCategory!=='downhill-mtb'&&a.mtbMode!=='downhill';const metrics=a.distanceMi?`<p class="popup-meta">${escapeHtml(a.distanceMi)} mi${showGain&&a.elevationGainM?` · ${escapeHtml(Math.round(a.elevationGainM))} m gain`:''}${a.elapsedSeconds?` · ${escapeHtml(formatDuration(a.elapsedSeconds))} elapsed`:''}</p>`:'';return `<article class="popup-card"><p class="popup-kicker">${escapeHtml(subtypeFor(a))}</p><h3 class="popup-title">${escapeHtml(a.name)}</h3>${alias}<p class="popup-meta">${escapeHtml(primary)}${primary?' · ':''}${escapeHtml(a.location)}</p>${date}${metrics}<p class="popup-detail"><a href="${recordHref(a)}">Open record →</a></p></article>`}
function coordinateKey(a){return`${a.lat.toFixed(5)},${a.lon.toFixed(5)}`}
function primaryCategoryForGroup(group){const categories=group.map(publicLayerFor);if(categories.includes('skiing'))return'skiing';const unique=[...new Set(categories)];return unique.length===1?unique[0]:categories[0]||'adventures'}
function renderMarkers(items){markerLayer.clearLayers();state.markers.clear();const groups=new Map();items.filter(mapped).forEach(a=>{const k=coordinateKey(a);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(a)});groups.forEach(group=>{const first=group[0],category=primaryCategoryForGroup(group),color=CATEGORY[category]?.color||CATEGORY.adventures.color,mixed=new Set(group.map(publicLayerFor)).size>1;const marker=L.circleMarker([first.lat,first.lon],{radius:group.length>1?8:6,color:'#fff',weight:mixed?3:2,fillColor:color,fillOpacity:.9});marker.bindPopup(group.map(popupCard).join(''),{maxWidth:360});marker.addTo(markerLayer);group.forEach(x=>state.markers.set(x.id,marker))})}
function visibleRouteFeatures(items){if(!state.routes)return[];const ids=new Set(items.map(a=>a.id));return state.routes.features.filter(f=>(f.properties?.adventureIds||[]).some(id=>ids.has(id)))}
function baseRouteStyle(feature,category){const historical=feature.properties?.provenance==='historical-course';return{color:CATEGORY[category]?.color||'#17202a',weight:category==='summits'?3:4.5,opacity:historical?.64:.84,dashArray:historical?'8 6':null,lineCap:'round',lineJoin:'round'}}
function routeContainsId(layer,id){return(layer.feature?.properties?.adventureIds||[]).includes(id)}
function applyFocusStyles(){state.routeFeatureLayers.forEach(group=>group.eachLayer(layer=>{const feature=layer.feature||{},linked=(feature.properties?.adventureIds||[]).map(x=>state.adventures.find(a=>a.id===x)).filter(Boolean),category=publicLayerFor(linked[0]||{kind:'adventure'}),style=baseRouteStyle(feature,category),active=state.focusId&&routeContainsId(layer,state.focusId);layer.setStyle?.({...style,weight:active?Math.max(style.weight+3,7):style.weight,opacity:state.focusId?(active?1:.12):style.opacity});if(active)layer.bringToFront?.()}));state.markers.forEach((marker,id)=>{const active=state.focusId===id;marker.setStyle?.({radius:active?9:6,weight:active?3:2,fillOpacity:state.focusId?(active?.98:.28):.9,opacity:state.focusId?(active?1:.38):1});if(active)marker.bringToFront?.()});document.querySelectorAll('.adventure-item').forEach(el=>el.classList.toggle('is-context-muted',Boolean(state.focusId)&&el.dataset.id!==state.focusId))}
function setRouteEmphasis(id,on){if(on)state.focusId=id;else if(state.focusId===id)state.focusId=null;applyFocusStyles()}
function renderRoutes(items){routeLayer.clearLayers();state.routeLayers.clear();state.routeFeatureLayers.clear();state.focusId=null;visibleRouteFeatures(items).forEach(feature=>{const linked=(feature.properties?.adventureIds||[]).map(id=>state.adventures.find(x=>x.id===id)).filter(Boolean),category=publicLayerFor(linked[0]||{kind:'adventure'});const geo=L.geoJSON(feature,{style:baseRouteStyle(feature,category),onEachFeature:(f,layer)=>{layer.on('mouseover',()=>{const id=(f.properties?.adventureIds||[])[0];if(id)setRouteEmphasis(id,true)});layer.on('mouseout',()=>{const id=(f.properties?.adventureIds||[])[0];if(id)setRouteEmphasis(id,false)})}}).addTo(routeLayer);if(linked.length)geo.bindPopup(linked.map(popupCard).join(''),{maxWidth:360});(feature.properties?.adventureIds||[]).forEach(id=>{if(!state.routeLayers.has(id))state.routeLayers.set(id,[]);state.routeLayers.get(id).push(geo)});const fid=feature.id||feature.properties?.featureId||feature.properties?.id;if(fid)state.routeFeatureLayers.set(fid,geo)})}
function itemMeta(a){return[a.date?formatDate(a.date):'',a.location,subtypeFor(a),a.currentName?`now ${a.currentName}`:''].filter(Boolean).join(' · ')}
function itemValue(a){if(a.kind==='summit')return`${formatNumber(a.elevationFt)}′`;if(a.kind==='adventure')return a.distance||a.distanceMi?`${a.distanceMi||''}${a.distanceMi?' mi':''}`.trim():'';if(a.distanceMi)return`${a.distanceMi} mi`;return[a.year,a.distance].filter(Boolean).join(' · ')}
function focusAdventure(a){state.focusId=a.id;applyFocusStyles();const groups=state.routeLayers.get(a.id)||[];if(groups.length){const bounds=L.latLngBounds([]);groups.forEach(g=>g.eachLayer(layer=>{if(layer.getBounds)bounds.extend(layer.getBounds())}));if(bounds.isValid())map.fitBounds(bounds,{padding:[46,46],maxZoom:13});groups[0].openPopup?.();return}if(mapped(a)){map.flyTo([a.lat,a.lon],Math.max(map.getZoom(),a.kind==='summit'?9:8),{duration:.8});state.markers.get(a.id)?.openPopup()}}
function renderList(items){resultCount.textContent=`${items.length} shown`;adventureList.innerHTML='';items.slice().sort((a,b)=>{const ay=recordYear(a)||0,by=recordYear(b)||0;if(by!==ay)return by-ay;if(a.kind!==b.kind)return a.kind==='summit'?-1:1;if(a.kind==='summit')return(b.elevationFt??0)-(a.elevationFt??0);return a.name.localeCompare(b.name)}).forEach(a=>{const category=publicLayerFor(a),button=document.createElement('button');button.type='button';button.dataset.id=a.id;button.className=`adventure-item${mapped(a)||state.routeLayers.has(a.id)?'':' is-unmapped'}`;button.innerHTML=`<span class="item-dot" style="background:${CATEGORY[category]?.color||CATEGORY.adventures.color}"></span><span><span class="item-title">${escapeHtml(a.name)}</span><span class="item-meta">${escapeHtml(itemMeta(a))}</span></span><span class="item-value">${escapeHtml(itemValue(a))}</span>`;if(mapped(a)||state.routeLayers.has(a.id)){button.addEventListener('click',()=>focusAdventure(a));button.addEventListener('mouseenter',()=>setRouteEmphasis(a.id,true));button.addEventListener('mouseleave',()=>setRouteEmphasis(a.id,false));button.addEventListener('focus',()=>setRouteEmphasis(a.id,true));button.addEventListener('blur',()=>setRouteEmphasis(a.id,false))}adventureList.appendChild(button)})}
function walkCoordinates(coords,bounds){if(!Array.isArray(coords))return;if(typeof coords[0]==='number'){const[lon,lat]=coords;if(Number.isFinite(lat)&&Number.isFinite(lon))bounds.extend([lat,lon]);return}coords.forEach(c=>walkCoordinates(c,bounds))}
function fitVisible(items){state.focusId=null;const bounds=L.latLngBounds([]);items.filter(mapped).forEach(x=>bounds.extend([x.lat,x.lon]));visibleRouteFeatures(items).forEach(f=>walkCoordinates(f.geometry?.coordinates,bounds));if(bounds.isValid())map.fitBounds(bounds,{padding:[38,38],maxZoom:8});applyFocusStyles()}
function render(){const items=filteredAdventures();renderRoutes(items);renderMarkers(items);renderList(items)}
function applyAndFit(){render();fitVisible(filteredAdventures())}
function initYearControls(){const years=[...new Set(state.adventures.map(recordYear).filter(Boolean))].sort((a,b)=>a-b);const options=years.map(y=>`<option value="${y}">${y}</option>`).join('');yearFrom.insertAdjacentHTML('beforeend',options);yearTo.insertAdjacentHTML('beforeend',options);yearFrom.addEventListener('change',()=>{state.yearFrom=yearFrom.value?Number(yearFrom.value):null;if(state.yearTo&&state.yearFrom&&state.yearFrom>state.yearTo){state.yearTo=state.yearFrom;yearTo.value=String(state.yearTo)}applyAndFit()});yearTo.addEventListener('change',()=>{state.yearTo=yearTo.value?Number(yearTo.value):null;if(state.yearFrom&&state.yearTo&&state.yearTo<state.yearFrom){state.yearFrom=state.yearTo;yearFrom.value=String(state.yearFrom)}applyAndFit()});yearReset.addEventListener('click',()=>{state.yearFrom=null;state.yearTo=null;yearFrom.value='';yearTo.value='';applyAndFit()})}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{state.filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('is-active',x===button));applyAndFit()}));searchInput.addEventListener('input',()=>{state.search=searchInput.value;render()});searchInput.addEventListener('keydown',e=>{if(e.key==='Enter')fitVisible(filteredAdventures())});fitButton.addEventListener('click',()=>fitVisible(filteredAdventures()));map.on('click',()=>{state.focusId=null;applyFocusStyles()});
async function init(){try{const[adventures,routes]=await Promise.all([AdventureCatalog.load(),AdventureRoutes.loadAll()]);state.adventures=adventures;state.routes=routes;document.getElementById('summitCount').textContent=state.adventures.filter(x=>x.kind==='summit').length;document.getElementById('raceCount').textContent=state.adventures.filter(x=>x.kind==='race').length;document.getElementById('routeCount').textContent=new Set(state.routes.features.flatMap(f=>f.properties?.adventureIds||[])).size;initYearControls();render();fitVisible(state.adventures);setTimeout(()=>map.invalidateSize({pan:false}),100)}catch(error){adventureList.innerHTML=`<p>Adventure data could not be loaded. ${escapeHtml(error.message)}</p>`;console.error(error)}}init();
