(()=>{
 const A=window.AdventureSite;if(!A)return;const esc=A.esc,pct=(n,d)=>d?Math.round(n/d*100):0;
 const bar=(label,value,max,meta='')=>`<div style="display:grid;grid-template-columns:minmax(72px,120px) 1fr auto;gap:10px;align-items:center;margin:8px 0"><span>${esc(label)}</span><div style="height:10px;border-radius:999px;background:rgba(127,127,127,.18);overflow:hidden"><div style="height:100%;width:${max?Math.max(3,value/max*100):0}%;background:currentColor;border-radius:999px"></div></div><strong>${esc(meta||String(value))}</strong></div>`;
 const raceMiles=r=>{const official=Number(r.officialDistanceMi);if(Number.isFinite(official)&&official>0)return official;const normalized=Number(r.distanceInfo?.mi);if(Number.isFinite(normalized)&&normalized>0)return normalized;const fallback=Number(r.distanceMi);return Number.isFinite(fallback)&&fallback>0?fallback:0;};
 A.load().then(all=>{const races=all.filter(a=>a.kind==='race').sort((a,b)=>(a.date||'').localeCompare(b.date||''));if(!races.length)return;const host=document.getElementById('timeline');if(!host)return;
 const years=new Map(),milesByYear=new Map(),disc=new Map();let cumulative=0;const cumulativeRows=[];
 races.forEach(r=>{const y=Number(r.year||r.date?.slice(0,4)),miles=raceMiles(r);if(y){years.set(y,(years.get(y)||0)+1);milesByYear.set(y,(milesByYear.get(y)||0)+miles)}const d=r.discipline||'road';disc.set(d,(disc.get(d)||0)+1);cumulative+=miles;cumulativeRows.push([r.date?.slice(0,4)||r.year||'?',cumulative])});
 const peak=[...years.entries()].sort((a,b)=>b[1]-a[1]||a[0]-b[0])[0],knownMiles=[...milesByYear.values()].reduce((a,b)=>a+b,0);const offroad=(disc.get('trail')||0)+(disc.get('nordic')||0)+(disc.get('mountain-bike')||0);const marathons=disc.get('marathon')||0;
 const recurring=new Map();races.forEach(r=>{const key=(r.eventSeries||r.name||'').replace(/\b(19|20)\d{2}\b/g,'').replace(/\s+/g,' ').trim();if(key)recurring.set(key,(recurring.get(key)||0)+1)});const repeat=[...recurring.entries()].filter(x=>x[1]>1).sort((a,b)=>b[1]-a[1]).slice(0,6);
 const overview=document.createElement('section');overview.className='sport-detail';overview.innerHTML=`<div class="sport-detail-head"><h2>Race history at a glance</h2><p>A statistical view generated directly from the canonical race archive. Official race distances are used when verified; GPS distance is the fallback.</p></div><div class="sport-detail-grid"><article class="sport-panel"><small>Known race mileage</small><strong>${knownMiles?knownMiles.toFixed(1)+' mi':'—'}</strong><p>Only records with normalized distance data.</p></article><article class="sport-panel"><small>Busiest year</small><strong>${peak?peak[0]:'—'}</strong><p>${peak?peak[1]+' recorded races':''}</p></article><article class="sport-panel"><small>Marathon share</small><strong>${pct(marathons,races.length)}%</strong><p>${marathons} of ${races.length} race records</p></article><article class="sport-panel"><small>Off-road racing</small><strong>${offroad}</strong><p>Trail, Nordic, and MTB races</p></article></div>${repeat.length?`<div class="detail-callout"><strong>Recurring race families</strong><p>${repeat.map(([n,c])=>`${esc(n)} × ${c}`).join(' · ')}</p></div>`:''}`;host.parentNode.insertBefore(overview,host);
 const maxYear=Math.max(...years.values()),yearBars=[...years.entries()].sort((a,b)=>a[0]-b[0]).map(([y,n])=>bar(String(y),n,maxYear,`${n}`)).join('');const labels={'marathon':'Marathon','road':'Road','trail':'Trail','relay':'Relay','nordic':'Nordic','mountain-bike':'MTB'},maxDisc=Math.max(...disc.values());const discBars=[...disc.entries()].sort((a,b)=>b[1]-a[1]).map(([d,n])=>bar(labels[d]||d,n,maxDisc,`${n}`)).join('');
 const analytics=document.createElement('section');analytics.className='sport-detail';analytics.innerHTML=`<div class="sport-detail-head"><h2>The shape of the race archive</h2><p>Chronology and discipline mix, calculated from the same records that power the timeline below.</p></div><div class="sport-detail-grid"><article class="sport-panel wide"><small>Races by year</small>${yearBars}</article><article class="sport-panel wide"><small>Discipline mix</small>${discBars}</article></div><div class="detail-callout"><strong>Cumulative known race distance</strong><p>${knownMiles?`${knownMiles.toFixed(1)} miles currently documented across ${races.filter(r=>raceMiles(r)>0).length} races. This total grows only when a race distance is actually known.`:'Distance normalization is still in progress.'}</p></div>`;host.parentNode.insertBefore(analytics,host);
 }).catch(e=>console.error('Race stats',e));
})();
