import fs from 'node:fs';
import path from 'node:path';
import { test, expect } from '@playwright/test';
import { SITE_ORIGIN, siteRoutes } from '../scripts/lib/site-routes.mjs';

const duplicateValues = values => [...new Set(values.filter((value, index) => values.indexOf(value) !== index))];

test('route registry has one owner for every public path', async () => {
  for (const field of ['key', 'path', 'source']) {
    const values = siteRoutes.map(route => route[field]).filter(Boolean);
    expect(duplicateValues(values), `duplicate route ${field}`).toEqual([]);
  }

  for (const route of siteRoutes) {
    expect(fs.existsSync(route.source), `${route.key} source exists`).toBe(true);
    if (route.path !== '/') {
      expect(route.path.startsWith('/'), `${route.key} path starts with /`).toBe(true);
      expect(route.path.endsWith('/'), `${route.key} path has no trailing /`).toBe(false);
      expect(route.path.includes('.html'), `${route.key} canonical path is extensionless`).toBe(false);
    }
  }
});

test('generated clean routes own their directory outputs', async () => {
  for (const route of siteRoutes.filter(route => route.generated)) {
    expect(route.dir, `${route.key} declares output dir`).toBeTruthy();
    expect(route.path, `${route.key} path matches output dir`).toBe(`/${route.dir}`);
    expect(path.dirname(route.source), `${route.key} source is root-level`).toBe('.');
    expect(path.extname(route.source), `${route.key} source is HTML`).toBe('.html');
    expect(route.browserRewrite, `${route.key} compatibility source rewrites`).toBe(true);

    const output = path.join(route.dir, 'index.html');
    expect(fs.existsSync(output), `${route.key} generated output exists`).toBe(true);
    const html = fs.readFileSync(output, 'utf8');
    expect(html, `${route.key} generated ownership marker`).toContain('<!-- generated by scripts/build-static-site.mjs; do not hand-edit -->');
    expect(html, `${route.key} canonical tag`).toContain(`<link rel="canonical" href="${SITE_ORIGIN}${route.path}">`);
  }
});

test('direct clean routes are owned by their directory index', async () => {
  for (const route of siteRoutes.filter(route => !route.generated && route.dir)) {
    expect(route.source, `${route.key} direct source`).toBe(`${route.dir}/index.html`);
    expect(route.path, `${route.key} direct path`).toBe(`/${route.dir}`);
    expect(route.browserRewrite, `${route.key} direct route does not rewrite itself`).toBe(false);
  }
});
