import fs from 'node:fs';
import path from 'node:path';
import { test, expect } from '@playwright/test';
import { SITE_ORIGIN, siteRoutes, generatedRoutes, directRoutes } from '../scripts/lib/site-routes.mjs';

const PUBLICATION_TYPES = new Set(['root', 'generated-clean', 'direct-clean']);
const duplicateValues = values => [...new Set(values.filter((value, index) => values.indexOf(value) !== index))];

test('every registered route has one explicit publication role', async () => {
  for (const field of ['key', 'path', 'source']) {
    const values = siteRoutes.map(route => route[field]).filter(Boolean);
    expect(duplicateValues(values), `duplicate route ${field}`).toEqual([]);
  }

  for (const route of siteRoutes) {
    expect(PUBLICATION_TYPES.has(route.publication), `${route.key} publication type`).toBe(true);
    expect(fs.existsSync(route.source), `${route.key} source exists`).toBe(true);
    if (route.path !== '/') {
      expect(route.path.startsWith('/'), `${route.key} path starts with /`).toBe(true);
      expect(route.path.endsWith('/'), `${route.key} path has no trailing slash`).toBe(false);
      expect(route.path.includes('.html'), `${route.key} canonical path is extensionless`).toBe(false);
    }
  }
});

test('generated-clean routes own generated directory outputs', async () => {
  expect(generatedRoutes.map(route => route.key).sort()).toEqual(siteRoutes.filter(route => route.generated).map(route => route.key).sort());

  for (const route of generatedRoutes) {
    expect(route.generated, `${route.key} legacy generated flag matches publication role`).toBe(true);
    expect(route.dir, `${route.key} output directory`).toBeTruthy();
    expect(route.path, `${route.key} canonical path`).toBe(`/${route.dir}`);
    expect(path.dirname(route.source), `${route.key} source is root-level`).toBe('.');
    expect(path.extname(route.source), `${route.key} source is HTML`).toBe('.html');
    expect(route.browserRewrite, `${route.key} compatibility source rewrites`).toBe(true);

    const output = path.join(route.dir, 'index.html');
    expect(fs.existsSync(output), `${route.key} generated output exists`).toBe(true);
    const html = fs.readFileSync(output, 'utf8');
    expect(html).toContain('<!-- generated by scripts/build-static-site.mjs; do not hand-edit -->');
    expect(html).toContain(`<link rel="canonical" href="${SITE_ORIGIN}${route.path}">`);
  }
});

test('direct publication roles do not masquerade as generated outputs', async () => {
  expect(directRoutes.length).toBeGreaterThan(0);
  for (const route of directRoutes) {
    expect(route.generated, `${route.key} direct route is not generated`).toBe(false);
    if (route.publication === 'root') {
      expect(route.path).toBe('/');
      expect(route.source).toBe('index.html');
      continue;
    }
    expect(route.publication).toBe('direct-clean');
    expect(route.dir, `${route.key} direct directory`).toBeTruthy();
    expect(route.source, `${route.key} directory index owner`).toBe(`${route.dir}/index.html`);
    expect(route.path, `${route.key} direct clean path`).toBe(`/${route.dir}`);
    expect(route.browserRewrite, `${route.key} direct route does not rewrite itself`).toBe(false);
  }
});
