#!/usr/bin/env python3
"""Advance the Strava ingest watermark after an update queue has been reviewed.

Usage:
  python3 scripts/advance_strava_state.py tmp/update-queue.json --confirm-reviewed

This command does not publish activity records. It only records that the supplied
Strava snapshot has been fully reviewed so those activities do not reappear in the
next incremental scan.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_STATE = ROOT / "data" / "ingest-state.json"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def parse_dt(value: str | None) -> datetime | None:
    if not value:
        return None
    return datetime.fromisoformat(value)


def main() -> None:
    parser = argparse.ArgumentParser(description="Advance the reviewed Strava snapshot watermark.")
    parser.add_argument("queue", help="Review queue generated by scan_strava_export.py")
    parser.add_argument("--state", default=str(DEFAULT_STATE), help="Ingest-state JSON path")
    parser.add_argument("--confirm-reviewed", action="store_true", help="Required acknowledgement that the snapshot was reviewed")
    args = parser.parse_args()

    if not args.confirm_reviewed:
        raise SystemExit("Refusing to advance state without --confirm-reviewed")

    queue_path = Path(args.queue).expanduser().resolve()
    state_path = Path(args.state).expanduser().resolve()
    if not queue_path.exists():
        raise SystemExit(f"Queue not found: {queue_path}")

    queue = load_json(queue_path)
    proposal = queue.get("stateProposal")
    if not proposal:
        raise SystemExit("Queue does not contain a stateProposal")

    current = load_json(state_path) if state_path.exists() else {}
    old_dt = parse_dt(current.get("lastSeenActivityLocalDateTime"))
    new_dt = parse_dt(proposal.get("lastSeenActivityLocalDateTime"))
    if old_dt and new_dt and new_dt < old_dt:
        raise SystemExit("Refusing to move the Strava ingest watermark backward")

    required = ["snapshotOn", "activityCount", "lastSeenActivityLocalDateTime", "seenAtWatermarkActivityIdHashes"]
    missing = [key for key in required if proposal.get(key) in (None, "")]
    if missing:
        raise SystemExit(f"stateProposal is missing required fields: {', '.join(missing)}")

    state_path.parent.mkdir(parents=True, exist_ok=True)
    state_path.write_text(json.dumps(proposal, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Advanced Strava ingest state to {proposal['lastSeenActivityLocalDateTime']} ({proposal['activityCount']} activities in snapshot).")
    print("Run npm run validate:data before committing.")


if __name__ == "__main__":
    main()
