import fs from 'node:fs/promises';

const [routes,template]=await Promise.all([
  fs.readFile('site-routes.js','utf8'),
  fs.readFile('shared.template.js','utf8')
]);
const marker='// generated by scripts/build-shared.mjs from site-routes.js + shared.template.js; do not hand-edit\n';
const output=`${marker}${routes.trim()}\n\n${template.trim()}\n`;
await fs.writeFile('shared.js',output);
console.log('Generated shared.js from the canonical site route registry and shared shell template.');
