import fs from 'node:fs';
import { SITE_ORIGIN, siteRoutes, sitemapRoutes } from './lib/site-routes.mjs';

const shared=fs.readFileSync('shared.js','utf8');
const sharedTemplate=fs.readFileSync('shared.template.js','utf8');
const routeSource=fs.readFileSync('site-routes.js','utf8');
const fallback=fs.readFileSync('404.html','utf8');
const mapApp=fs.readFileSync('app.js','utf8');
const mapApi=fs.readFileSync('adventure-map-api.js','utf8');
const mapPage=fs.readFileSync('map.html','utf8');
const chapterMap=fs.readFileSync('chapter-map.js','utf8');
const detail=fs.readFileSync('detail.html','utf8');
const recordRenderer=fs.readFileSync('record-renderer.js','utf8');
const worldMajors=fs.readFileSync('world-majors.js','utf8');
const worldMajorsPassport=fs.readFileSync('world-majors-passport.css','utf8');
const sitemap=fs.readFileSync('sitemap.xml','utf8');
const publicPages=[...new Set([...siteRoutes.map(route=>route.source),'detail.html','404.html'])];
const errors=[];

const generatedMarker='// generated by scripts/build-shared.mjs from site-routes.js + shared.template.js; do not hand-edit\n';
const expectedShared=`${generatedMarker}${routeSource.trim()}\n\n${sharedTemplate.trim()}\n`;
if(shared!==expectedShared)errors.push('shared.js is not the current generated combination of site-routes.js and shared.template.js');
if(!shared.includes('window.AdventureSiteRoutes'))errors.push('generated shared shell does not bootstrap the canonical browser route registry');
if(!sharedTemplate.includes('const routeRegistry=window.AdventureSiteRoutes'))errors.push('shared shell template does not consume the canonical browser route registry');
if(!sharedTemplate.includes("siteRoutes.filter(route=>route.navGroup==='primary')")||!sharedTemplate.includes("siteRoutes.filter(route=>route.navGroup==='activity')"))errors.push('shared navigation is not derived from route-registry nav groups');
if(/const\s+(?:PUBLIC_PATHS|PRIMARY|AUX|ACTIVITIES)\s*=\s*[\[{]/.test(sharedTemplate))errors.push('shared shell template reintroduced an independent route/navigation table');
if(!sharedTemplate.includes('`/record/${encodeURIComponent(record.slug || record.id)}/`'))errors.push('shared shell does not emit clean production record routes');
if(!sharedTemplate.includes("assetHref('ux-polish.css')"))errors.push('shared shell must load the cross-chapter UX polish stylesheet');

if(/location\.(replace|assign)|detail\.html\?record=|clean\.match\(\/\^record/.test(fallback))errors.push('404.html must be a normal not-found page, not a clean-route resolver');
if(!fallback.includes('That page is not in the archive'))errors.push('404.html missing normal not-found message');
if(!mapApp.includes("location.hostname==='adventures.alexlford.com'"))errors.push('map app does not emit clean production record links');
if(!mapPage.includes('AdventureSiteRoutes'))errors.push('map page navigation must consume the canonical route registry');
if(/const\s+routes\s*=\s*\{[^}]*index\.html/.test(mapPage))errors.push('map page reintroduced an independent public-route table');
if(!mapPage.includes('<script src="app.js"></script><script src="adventure-map-api.js"></script>'))errors.push('map page must attach AdventureMap API immediately after the core app');
if(!mapPage.includes('<script src="adventure-map-api.js"></script><script src="map-url-state.js"></script>'))errors.push('map extensions must load after the stable AdventureMap API');
if(!mapApi.includes('window.AdventureMap = Object.freeze(api)'))errors.push('adventure-map-api.js must expose a frozen AdventureMap contract');
for(const method of ['filteredRecords','visibleRoutes','popupHtml','focus','emphasize','clearFocus','fit','refresh','setViewState'])if(!mapApi.includes(`${method}(`)&&!mapApi.includes(`${method},`))errors.push(`AdventureMap API missing ${method}`);
if(mapPage.includes('notable.js')||fs.existsSync('notable.js'))errors.push('retired notable.js compatibility script must not ship');
if(!chapterMap.includes('const A = window.AdventureSite')||!chapterMap.includes('const esc = A.esc'))errors.push('chapter map must use AdventureSite shared helpers');
if(!chapterMap.includes("A.pageHref('map.html')")||!chapterMap.includes('A.recordHref(item)'))errors.push('chapter map must use shared page and record URL helpers');
if(chapterMap.includes("location.hostname === 'adventures.alexlford.com'")||chapterMap.includes('const production ='))errors.push('chapter map must not duplicate production-host routing logic');
if(!chapterMap.includes('options?.mapLayer || pageLayer')||!chapterMap.includes('?layer=${encodeURIComponent(layer)}'))errors.push('chapter map must preserve chapter-aware full-map deep links');
if(!chapterMap.includes('const passiveMobile =')||!chapterMap.includes('dragging:!passiveMobile')||!chapterMap.includes('fitAll(){ fitRecords(currentRecords); }')||!chapterMap.includes('focus(item,zoom='))errors.push('chapter map must preserve passive-mobile, fit-all, and focus behavior');
if(!detail.includes('src="record-renderer.js"'))errors.push('detail page must load the single-pass record renderer');
if(!detail.includes('href="detail-phase4.css"')||!detail.includes('href="story-themes.css"')||!detail.includes('href="record-media.css"'))errors.push('detail page must load detail presentation styles directly');
for(const legacy of ['detail-phase4.js','story-detail.js','world-major-detail.js','record-media.js','clean-route-normalizer.js']){
  if(detail.includes(`src="${legacy}"`))errors.push(`detail page still loads legacy patch script ${legacy}`);
  if(shared.includes(`src='${legacy}'`)||shared.includes(`src="${legacy}"`))errors.push(`shared.js still injects legacy patch script ${legacy}`);
}
if(fs.existsSync('world-majors-stamp-fix.js'))errors.push('retired World Majors patch script must not ship');
if(worldMajors.includes('fitPassportCards')||worldMajors.includes('--passport-card-height'))errors.push('World Majors card sizing must remain CSS-only');
if(worldMajorsPassport.includes('--passport-card-height'))errors.push('World Majors passport CSS must not depend on a runtime-measured height variable');
if(!worldMajorsPassport.includes('grid-auto-rows:1fr'))errors.push('World Majors passport CSS must equalize card rows through the grid');
if(recordRenderer.includes('MutationObserver'))errors.push('record renderer must not depend on MutationObserver DOM patching');
if(!recordRenderer.includes("A.pageHref('map.html')"))errors.push('record renderer map action is not production-safe');
if(!recordRenderer.includes('await renderRecordMap(record)'))errors.push('record renderer must finish relative route loading before URL canonicalization');
if(!recordRenderer.includes("history.replaceState(null, '', A.recordHref(record))"))errors.push('record renderer does not restore the clean record URL after data and map loading');
if(!recordRenderer.includes('A.refreshMeta(description)'))errors.push('record renderer does not refresh canonical/share metadata');
if(/https:\/\/adventures\.alexlford\.com\/[a-z-]+\.html/.test(sitemap))errors.push('sitemap still publishes .html URLs');
for(const route of sitemapRoutes){
  const url=route.path==='/'?`${SITE_ORIGIN}/`:`${SITE_ORIGIN}${route.path}`;
  if(!sitemap.includes(url))errors.push(`sitemap missing registered public route ${route.path}`);
}
for(const file of publicPages){
  const text=fs.readFileSync(file,'utf8');
  if(/\bAlmanac\b/.test(text))errors.push(`${file} exposes retired Almanac branding; use Adventures, Stories, Explore, records, or archive as appropriate`);
}
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log(`Canonical route-registry validation passed for ${siteRoutes.length} public routes with a stable AdventureMap runtime boundary.`);
