import fs from 'node:fs';
const shared=fs.readFileSync('shared.js','utf8');
const fallback=fs.readFileSync('404.html','utf8');
const normalizer=fs.readFileSync('clean-route-normalizer.js','utf8');
const mapApp=fs.readFileSync('app.js','utf8');
const mapPage=fs.readFileSync('map.html','utf8');
const mapEnhancements=fs.readFileSync('map-enhancements.js','utf8');
const routeCatalogJs=fs.readFileSync('route-catalog.js','utf8');
const routeCatalog=fs.readFileSync('data/route-catalog.json','utf8');
const detail=fs.readFileSync('detail.html','utf8');
const sitemap=fs.readFileSync('sitemap.xml','utf8');
const publicPages=['index.html','map.html','activities.html','timeline.html','races.html','summits.html','skiing.html','nordic.html','mountain-biking.html','adventures.html','detail.html','404.html'];
const cleanRoutes={home:'/',map:'/map',explore:'/explore',timeline:'/timeline',races:'/races',summits:'/summits',skiing:'/skiing',nordic:'/nordic',mtb:'/mtb',stories:'/stories'};
const errors=[];
if(!shared.includes("productionHost='adventures.alexlford.com'"))errors.push('shared.js production host is not adventures.alexlford.com');
if(!shared.includes('`/record/${encodeURIComponent(record.slug || record.id)}/`'))errors.push('shared.js does not emit clean production record routes');
if(!shared.includes('const PUBLIC_PATHS='))errors.push('shared.js does not define clean production page routes');
for(const route of Object.values(cleanRoutes))if(!shared.includes(`'${route}'`)&&!shared.includes(`:${JSON.stringify(route)}`))errors.push(`shared.js missing clean public route ${route}`);
if(!fallback.includes("clean.match(/^record\\/([^/]+)$/)"))errors.push('404.html does not recognize /record/<slug>/ routes');
for(const [route,file] of Object.entries({home:'index.html',map:'map.html',explore:'activities.html',timeline:'timeline.html',races:'races.html',summits:'summits.html',skiing:'skiing.html',nordic:'nordic.html',mtb:'mountain-biking.html',stories:'adventures.html'}))if(!fallback.includes(`${route}:'${file}'`))errors.push(`404.html missing route mapping for ${route}`);
if(normalizer.includes('history.replaceState'))errors.push('record normalizer must not change browser history before relative data/map fetches finish');
if(!normalizer.includes('link[rel="canonical"]')||!normalizer.includes("meta[property=\"og:url\"]"))errors.push('record normalizer does not publish clean canonical/share URLs');
if(!mapApp.includes('AdventureRoutes.loadAll()'))errors.push('map app must load the complete canonical route catalog before rendering');
if(mapApp.includes("fetch('data/routes.geojson')"))errors.push('map app must not bypass the canonical route catalog');
if(!mapApp.includes('recordHref=A.recordHref')||!mapApp.includes('formatDate=A.formatDate')||!mapApp.includes('escapeHtml=A.esc'))errors.push('map app must use AdventureSite shared URL and formatting helpers');
if(/function\s+(recordHref|formatDate|formatDuration|escapeHtml)\b/.test(mapApp))errors.push('map app must not reimplement shared URL, date, duration, or escaping helpers');
if(!mapApp.includes('mapEntities:[]')||!mapApp.includes('loadSkiResortEntities()'))errors.push('map app must model ski resorts as explicit map entities loaded before first render');
if(!mapApp.includes('function racePopupCard')||!mapApp.includes('officialDistanceLabel'))errors.push('map app must render official race results in the core popup renderer');
if(!mapPage.includes('href="index.html"')||!mapPage.includes('src="shared.js"'))errors.push('map page must keep relative staging links and load the shared site shell');
if(mapPage.indexOf('src="shared.js"')>mapPage.indexOf('src="app.js"'))errors.push('map page must load shared.js before app.js');
if(mapPage.includes('notable.js')||fs.existsSync('notable.js'))errors.push('obsolete notable.js map extension must remain removed');
if(mapPage.includes('expansion.js')||fs.existsSync('expansion.js'))errors.push('obsolete supplemental route loader must remain removed');
if(mapPage.includes('ski-map.js')||fs.existsSync('ski-map.js'))errors.push('obsolete ski-map.js patch module must remain removed');
if(mapPage.includes('official-results-ui.js')||fs.existsSync('official-results-ui.js'))errors.push('obsolete official-results-ui.js patch module must remain removed');
if(mapEnhancements.includes('detail.html?id=')||mapEnhancements.includes('window.popupCard'))errors.push('map enhancements must not wrap popupCard or inject legacy record links');
if(!routeCatalogJs.includes('cfg.polylineFiles')||!routeCatalog.includes('"data/activity-route-polylines.json"'))errors.push('route catalog must own day-level activity polylines');
if(detail.includes('payloads.flatMap')||!detail.includes('const features=(collection.features||[])'))errors.push('detail page must consume AdventureRoutes.loadAll() as one merged FeatureCollection');
if(!detail.includes("A.pageHref('map.html')"))errors.push('detail page map action is not production-safe');
if(!detail.includes("history.replaceState(null,'',A.recordHref(a))"))errors.push('detail page does not restore the clean record URL after data and map loading');
if(/https:\/\/adventures\.alexlford\.com\/[a-z-]+\.html/.test(sitemap))errors.push('sitemap still publishes .html URLs');
for(const route of Object.values(cleanRoutes).filter(x=>x!=='/'))if(!sitemap.includes(`https://adventures.alexlford.com${route}`))errors.push(`sitemap missing clean route ${route}`);
for(const file of publicPages){
  const text=fs.readFileSync(file,'utf8');
  if(/\bAlmanac\b/.test(text))errors.push(`${file} exposes retired Almanac branding; use Adventures, Stories, Explore, records, or archive as appropriate`);
}
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log('Clean routing and Adventures branding validation passed.');
